/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaskPlannerRouteImport } from './routes/task-planner'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResearchAssistantRouteImport } from './routes/research-assistant'
import { Route as MeetingSummarizerRouteImport } from './routes/meeting-summarizer'
import { Route as EmailGeneratorRouteImport } from './routes/email-generator'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TaskPlannerRoute = TaskPlannerRouteImport.update({
  id: '/task-planner',
  path: '/task-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchAssistantRoute = ResearchAssistantRouteImport.update({
  id: '/research-assistant',
  path: '/research-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingSummarizerRoute = MeetingSummarizerRouteImport.update({
  id: '/meeting-summarizer',
  path: '/meeting-summarizer',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailGeneratorRoute = EmailGeneratorRouteImport.update({
  id: '/email-generator',
  path: '/email-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/meeting-summarizer': typeof MeetingSummarizerRoute
  '/research-assistant': typeof ResearchAssistantRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/task-planner': typeof TaskPlannerRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/meeting-summarizer': typeof MeetingSummarizerRoute
  '/research-assistant': typeof ResearchAssistantRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/task-planner': typeof TaskPlannerRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/meeting-summarizer': typeof MeetingSummarizerRoute
  '/research-assistant': typeof ResearchAssistantRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/task-planner': typeof TaskPlannerRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/email-generator'
    | '/meeting-summarizer'
    | '/research-assistant'
    | '/sitemap.xml'
    | '/task-planner'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/email-generator'
    | '/meeting-summarizer'
    | '/research-assistant'
    | '/sitemap.xml'
    | '/task-planner'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/email-generator'
    | '/meeting-summarizer'
    | '/research-assistant'
    | '/sitemap.xml'
    | '/task-planner'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  EmailGeneratorRoute: typeof EmailGeneratorRoute
  MeetingSummarizerRoute: typeof MeetingSummarizerRoute
  ResearchAssistantRoute: typeof ResearchAssistantRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TaskPlannerRoute: typeof TaskPlannerRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/task-planner': {
      id: '/task-planner'
      path: '/task-planner'
      fullPath: '/task-planner'
      preLoaderRoute: typeof TaskPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-assistant': {
      id: '/research-assistant'
      path: '/research-assistant'
      fullPath: '/research-assistant'
      preLoaderRoute: typeof ResearchAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-summarizer': {
      id: '/meeting-summarizer'
      path: '/meeting-summarizer'
      fullPath: '/meeting-summarizer'
      preLoaderRoute: typeof MeetingSummarizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-generator': {
      id: '/email-generator'
      path: '/email-generator'
      fullPath: '/email-generator'
      preLoaderRoute: typeof EmailGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  EmailGeneratorRoute: EmailGeneratorRoute,
  MeetingSummarizerRoute: MeetingSummarizerRoute,
  ResearchAssistantRoute: ResearchAssistantRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TaskPlannerRoute: TaskPlannerRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
